// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Parse$BsJson = require("./parse.bs.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");
var Serialize$BsJson = require("./serialize.bs.js");

var Unexpected = Caml_exceptions.create("Demo-BsJson.Unexpected");

function test(param) {
  var jsonString = "{ \"toto\": \"😇\" }";
  console.log("Input", jsonString);
  var parsed = Parse$BsJson.parse(jsonString);
  if (parsed.tag) {
    console.log("Json parser error");
    return /* () */0;
  } else {
    console.log("Output", Serialize$BsJson.serialize(parsed[0]));
    return /* () */0;
  }
}

test(/* () */0);

exports.Unexpected = Unexpected;
exports.test = test;
/*  Not a pure module */
