// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$String = require("bs-platform/lib/js/string.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function serialize(json) {
  var _serialize = function (param) {
    if (typeof param === "number") {
      return "null";
    } else {
      switch (param.tag | 0) {
        case 0 : 
            if (param[0]) {
              return "true";
            } else {
              return "false";
            }
        case 1 : 
            return String(param[0]);
        case 2 : 
            return Pervasives.string_of_float(param[0]);
        case 3 : 
            return serialize_string(param[0]);
        case 4 : 
            var l = param[0];
            return "[" + ($$String.concat(",", List.map(_serialize, l)) + "]");
        case 5 : 
            var a = param[0];
            return "{" + ($$String.concat(",", List.map((function (param) {
                                return serialize_string(param[0]) + (":" + _serialize(param[1]));
                              }), a)) + "}");
        
      }
    }
  };
  var serialize_string = function (s) {
    return "\"" + (s + "\"");
  };
  return _serialize(json);
}

exports.serialize = serialize;
/* No side effect */
