// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Parse$BsGraphqlQueryParser = require("../src/parse.bs.js");

describe("Parser", (function () {
        return Jest.test("inline queries", (function (param) {
                      return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* :: */[
                                      /* Operation */[/* record */[/* typ : Query */0]],
                                      /* [] */0
                                    ]]), Jest.Expect[/* expect */0](Parse$BsGraphqlQueryParser.parse("{ Hello }")));
                    }));
      }));

/*  Not a pure module */
