// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Block = require("bs-platform/lib/js/block.js");
var Parser$BsGraphqlJsonParser = require("../src/parser.bs.js");

describe("parse", (function () {
        Jest.test("should parse a valid empty json object", (function (param) {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* Assoc */Block.__(5, [/* [] */0])]), Jest.Expect[/* expect */0](Parser$BsGraphqlJsonParser.parse("{}")));
              }));
        Jest.test("should parse a valid json list of values", (function (param) {
                return Jest.Expect[/* toEqual */12](/* Ok */Block.__(0, [/* List */Block.__(4, [/* :: */[
                                    /* Int */Block.__(1, [1]),
                                    /* :: */[
                                      /* String */Block.__(3, ["two"]),
                                      /* :: */[
                                        /* Float */Block.__(2, [3]),
                                        /* :: */[
                                          /* Assoc */Block.__(5, [/* :: */[
                                                /* tuple */[
                                                  "value",
                                                  /* Int */Block.__(1, [4])
                                                ],
                                                /* [] */0
                                              ]]),
                                          /* :: */[
                                            /* List */Block.__(4, [/* :: */[
                                                  /* Int */Block.__(1, [5]),
                                                  /* [] */0
                                                ]]),
                                            /* :: */[
                                              /* Bool */Block.__(0, [true]),
                                              /* :: */[
                                                /* Null */0,
                                                /* [] */0
                                              ]
                                            ]
                                          ]
                                        ]
                                      ]
                                    ]
                                  ]])]), Jest.Expect[/* expect */0](Parser$BsGraphqlJsonParser.parse("[1, \"two\", 3.0, { \"value\": 4 }, [5], true, null]")));
              }));
        return Jest.test("should be fast", (function (param) {
                      var start = new Date().getTime();
                      Parser$BsGraphqlJsonParser.parse("[{\"value\": 1}]");
                      var duration = new Date().getTime() - start;
                      return Jest.Expect[/* toBeLessThanOrEqual */8](1, Jest.Expect[/* expect */0](duration));
                    }));
      }));

/*  Not a pure module */
